export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_LANG = 'SET_LANG';
export const SET_THEME_MODE = 'SET_THEME_MODE';

export const SET_SNACKBAR_MODE = 'SET_SNACKBAR_MODE';

export const FETCH_TAGS_PENDING = 'FETCH_TAGS_PENDING';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGSS_SUCCESS';
export const FETCH_TAGS_ERROR = 'FETCH_TAGS_ERROR';

export const FETCH_TECHNICS_PENDING = 'FETCH_TECHNICS_PENDING';
export const FETCH_TECHNICS_SUCCESS = 'FETCH_TECHNICS_SUCCESS';
export const FETCH_TECHNICS_ERROR = 'FETCH_TECHNICS_ERROR';