export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_LANG = 'SET_LANG';
export const SET_THEME_MODE = 'SET_THEME_MODE';

export const SET_SNACKBAR_MODE = 'SET_SNACKBAR_MODE';

/*Get data*/
export const FETCH_TAGS_PENDING = 'FETCH_TAGS_PENDING';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGSS_SUCCESS';
export const FETCH_TAGS_ERROR = 'FETCH_TAGS_ERROR';

export const FETCH_TECHNICS_PENDING = 'FETCH_TECHNICS_PENDING';
export const FETCH_TECHNICS_SUCCESS = 'FETCH_TECHNICS_SUCCESS';
export const FETCH_TECHNICS_ERROR = 'FETCH_TECHNICS_ERROR';

export const FETCH_AVATARS_PENDING = 'FETCH_AVATARS_PENDING';
export const FETCH_AVATARS_SUCCESS = 'FETCH_AVATARS_SUCCESS';
export const FETCH_AVATARS_ERROR = 'FETCH_AVATARS_ERROR';

export const FETCH_USER_DATA_PENDING = 'FETCH_USER_DATA_PENDING';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR';

export const FETCH_USER_POSTS_PENDING = 'FETCH_USER_POSTS_PENDING';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_ERROR = 'FETCH_USER_POSTS_ERROR';

export const FETCH_CONNECT_POSTS_PENDING = 'FETCH_CONNECT_POSTS_PENDING';
export const FETCH_CONNECT_POSTS_SUCCESS = 'FETCH_CONNECT_POSTS_SUCCESS';
export const FETCH_CONNECT_POSTS_ERROR = 'FETCH_CONNECT_POSTS_ERROR';

export const FETCH_USER_MAP_PENDING = 'FETCH_USER_MAP_PENDING';
export const FETCH_USER_MAP_SUCCESS = 'FETCH_USER_MAP_SUCCESS';
export const FETCH_USER_MAP_ERROR = 'FETCH_USER_MAP_ERROR';

export const FETCH_RANDOM_USERS_PENDING = 'FETCH_RANDOM_USERS_PENDING';
export const FETCH_RANDOM_USERS_SUCCESS = 'FETCH_RANDOM_USERS_SUCCESS';
export const FETCH_RANDOM_USERS_ERROR = 'FETCH_RANDOM_USERS_ERROR';

/*Update data*/
export const FETCH_UPDATE_USER_DATA_PENDING = 'FETCH_UPDATE_USER_DATA_PENDING';
export const FETCH_UPDATE_USER_DATA_SUCCESS = 'FETCH_UPDATE_USER_DATA_SUCCESS';
export const FETCH_UPDATE_USER_DATA_ERROR = 'FETCH_UPDATE_USER_DATA_ERROR';
export const RESET_UPDATE_USER_DATA_ERROR = 'RESET_UPDATE_USER_DATA_ERROR';
export const RESET_UPDATE_USER_DATA = 'RESET_UPDATE_USER_DATA';

/*Create user*/
export const FETCH_CREATE_USER_PENDING = 'FETCH_CREATE_USER_PENDING';
export const FETCH_CREATE_USER_SUCCESS = 'FETCH_CREATE_USER_SUCCESS';
export const FETCH_CREATE_USER_ERROR = 'FETCH_CREATE_USER_ERROR';
export const RESET_CREATE_USER_ERROR = 'RESET_CREATE_USER_ERROR';